services:
  news-backend:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    env_file: server/.env
    environment:
      HOST: 0.0.0.0
      PORT: 80 
      NEXT_AUTH_URL: "http://127.0.0.1:80"
    ports:
      - "4000:80"
  news-client:
    build:
      context: client
      dockerfile: Dockerfile
    restart: always
    links:
      - news-backend
    env_file: client/.env
    environment:
      HOST: 0.0.0.0
      PORT: 80
      BACKEND_HOST: news-backend
      BACKEND_PORT: 80
      NEXT_AUTH: http://news-backend:4000
    ports:
      - "8000:80"
    
